name: Python CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.12.2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check file existence
      id: requirements
      uses: thebinaryfelix/check-file-existence-action@v1
      with:
        files: 'requirements.txt'

    - name: Install dependencies (if requirements.txt exists)
      if: steps.requirements.outputs.exists == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        py -m unittest
        echo "Tests executed"

    - name: Handle test results
      if: failure()
      run: |
        git reset --hard HEAD~1
        git checkout -b failures/${{ github.run_number }}
        git push origin failures/${{ github.run_number }}
        echo "Test failed, rolled back and pushed to failures branch"

    - name: Merge develop to main
      if: success()
      run: |
        git fetch origin
        git checkout main
        git merge --ff-only develop
        git push origin main
        echo "Test passed, merged to main"
